import { CardDetail } from '../models'

export const statsCards: CardDetail[] = [
    {
        title: 'goals',
        attributes: ['goals'],
        unit: 'goals',
        interval: { max: 3 },
        positionsNotAllowed: ['gk'],
    },
    {
        title: 'assists',
        attributes: ['assists'],
        unit: 'assists',
        interval: { max: 3 },
        positionsNotAllowed: ['gk'],
    },
    {
        title: 'savedShots',
        attributes: ['shotsOffTarget', 'goals'], // calculo
        unit: 'shots',
        interval: { max: 5 },
        positionsNotAllowed: ['gk'],
    },
    {
        title: 'shotsOffTarget',
        attributes: ['shotsOffTarget'],
        unit: 'shots',
        interval: { max: 10 },
        positionsNotAllowed: ['gk'],
    },
    {
        title: 'sufferedFouls',
        attributes: ['wasFouled'],
        unit: 'fouls',
        interval: { max: 15 },
        positionsNotAllowed: [],
    },
    {
        title: 'sufferedPenalties',
        attributes: ['penaltyWon'],
        unit: 'penalties',
        interval: { max: 0.5 },
        positionsNotAllowed: ['gk'],
    },
    // ------------- Defense -------------
    {
        title: 'savedPenalties',
        attributes: ['penaltySave'],
        unit: 'penalties',
        interval: { max: 0.5 },
        positionsNotAllowed: ['st', 'mid', 'wb', 'cb'],
    },
    {
        title: 'cleanSheets',
        attributes: ['cleanSheet'],
        unit: 'cleanSheet',
        interval: { max: 5 },
        positionsNotAllowed: ['st', 'mid'],
    },
    {
        title: 'saves',
        attributes: ['saves'],
        unit: 'saves',
        interval: { max: 8 },
        positionsNotAllowed: ['st', 'mid', 'wb', 'cb'],
    },
    {
        title: 'tackleWon',
        attributes: ['tacklesWon'],
        unit: 'tackleWon',
        interval: { max: 12 },
        positionsNotAllowed: ['gk'],
    },
    // -----------------------------------
    {
        title: 'penaltyLost',
        attributes: ['penaltiesTaken', 'penaltyGoals'],
        unit: 'penalties',
        interval: { max: 0.1 },
        positionsNotAllowed: ['gk'],
        negative: true,
    },
    {
        title: 'offsides',
        attributes: ['offsides'],
        unit: 'offsides',
        interval: { max: 6 },
        positionsNotAllowed: ['gk'],
        negative: true,
    },
    {
        title: 'ownGoals',
        attributes: ['ownGoals'],
        unit: 'goals',
        interval: { max: 0.2 },
        positionsNotAllowed: [],
        negative: true,
    },
    {
        title: 'redCard',
        attributes: ['redCards'],
        unit: 'cards',
        interval: { max: 1 },
        positionsNotAllowed: [],
        negative: true,
    },
    {
        title: 'yellowCards',
        attributes: ['yellowCards'],
        unit: 'cards',
        interval: { max: 3 },
        positionsNotAllowed: [],
        negative: true,
    },
    {
        title: 'goalsConceded',
        attributes: ['goalsConceded'],
        unit: 'goals',
        interval: { max: 1.5 },
        positionsNotAllowed: ['st', 'mid', 'wb', 'cb'],
        negative: true,
    },
    {
        title: 'fouls',
        attributes: ['fouls'],
        unit: 'fouls',
        interval: { max: 8 },
        positionsNotAllowed: [],
        negative: true,
    },
    {
        title: 'penaltiesConceded',
        attributes: ['penaltyConceded'],
        unit: 'penalties',
        interval: { max: 0.2 },
        positionsNotAllowed: [],
        negative: true,
    },
]
